"use client"

import { useState } from "react"
import { useTournament } from "@/lib/tournament-context"
import Image from "next/image"
import { getLogoUrl } from "@/lib/logo"

export function MatchCenter() {
  const { matches, teams } = useTournament()
  const [activeRound, setActiveRound] = useState(1)

  const groupMatches = matches.filter((m) => m.stage === "group")
  const knockoutMatches = matches.filter((m) => m.stage !== "group")

  const rounds = [1, 2, 3]
  const hasKnockout = knockoutMatches.length > 0

  const getTeam = (id: string) => teams.find((t) => t.id === id)

  if (matches.length === 0) {
    return (
      <section className="py-12">
        <h2 className="mb-8 text-center text-2xl font-bold tracking-tight text-foreground">
          Match Center
        </h2>
        <div className="flex flex-col items-center justify-center rounded-xl border border-border bg-card px-8 py-16 text-center">
          <p className="text-lg text-muted-foreground">
            No matches scheduled yet. The tournament schedule will appear here once generated by the admin.
          </p>
        </div>
      </section>
    )
  }

  return (
    <section className="py-12">
      <h2 className="mb-8 text-center text-2xl font-bold tracking-tight text-foreground">
        Match Center
      </h2>

      {/* Round Tabs */}
      <div className="mb-6 flex flex-wrap items-center justify-center gap-2">
        {rounds.map((round) => (
          <button
            key={round}
            onClick={() => setActiveRound(round)}
            className={`rounded-lg px-5 py-2 text-sm font-medium transition-all ${
              activeRound === round
                ? "bg-primary text-primary-foreground shadow-lg shadow-primary/20"
                : "bg-secondary text-muted-foreground hover:bg-secondary/80 hover:text-foreground"
            }`}
          >
            Round {round}
          </button>
        ))}
        {hasKnockout && (
          <button
            onClick={() => setActiveRound(4)}
            className={`rounded-lg px-5 py-2 text-sm font-medium transition-all ${
              activeRound === 4
                ? "bg-primary text-primary-foreground shadow-lg shadow-primary/20"
                : "bg-secondary text-muted-foreground hover:bg-secondary/80 hover:text-foreground"
            }`}
          >
            Knockout
          </button>
        )}
      </div>

      {/* Match Cards */}
      <div className="grid gap-4 sm:grid-cols-2">
        {activeRound <= 3
          ? groupMatches
              .filter((m) => m.round_number === activeRound)
              .map((match) => {
                const home = getTeam(match.home_team_id)
                const away = getTeam(match.away_team_id)
                if (!home || !away) return null
                return (
                  <MatchCard
                    key={match.id}
                    homeName={home.name}
                    homeLogo={home.logo_url}
                    awayName={away.name}
                    awayLogo={away.logo_url}
                    homeScore={match.home_score}
                    awayScore={match.away_score}
                    isCompleted={match.is_completed}
                    groupName={match.group_name}
                    label=""
                  />
                )
              })
          : knockoutMatches.map((match) => {
              const home = getTeam(match.home_team_id)
              const away = getTeam(match.away_team_id)
              const label =
                match.stage === "semi"
                  ? "Semi-Final"
                  : match.stage === "final"
                  ? "Final"
                  : ""
              return (
                <MatchCard
                  key={match.id}
                  homeName={home?.name ?? "TBD"}
                  homeLogo={home?.logo_url ?? ""}
                  awayName={away?.name ?? "TBD"}
                  awayLogo={away?.logo_url ?? ""}
                  homeScore={match.home_score}
                  awayScore={match.away_score}
                  isCompleted={match.is_completed}
                  groupName="Knockout"
                  label={label}
                />
              )
            })}
      </div>
    </section>
  )
}

function MatchCard({
  homeName,
  homeLogo,
  awayName,
  awayLogo,
  homeScore,
  awayScore,
  isCompleted,
  groupName,
  label,
}: {
  homeName: string
  homeLogo: string
  awayName: string
  awayLogo: string
  homeScore: number | null
  awayScore: number | null
  isCompleted: boolean
  groupName: string
  label: string
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-border bg-card transition-all hover:border-primary/30">
      <div className="flex items-center justify-between border-b border-border/50 bg-secondary/50 px-4 py-2">
        <span className="text-xs font-medium text-muted-foreground">{groupName}</span>
        {label && (
          <span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-semibold text-primary">
            {label}
          </span>
        )}
        <span
          className={`rounded-full px-2 py-0.5 text-xs font-medium ${
            isCompleted
              ? "bg-primary/10 text-primary"
              : "bg-secondary text-muted-foreground"
          }`}
        >
          {isCompleted ? "FT" : "Upcoming"}
        </span>
      </div>
      <div className="flex items-center justify-between px-4 py-5">
        {/* Home team */}
        <div className="flex flex-1 flex-col items-center gap-2">
          {homeLogo ? (
            <div className="relative h-12 w-12 overflow-hidden rounded-full">
              <Image src={getLogoUrl(homeLogo)} alt={homeName} fill className="object-cover" sizes="48px" />
            </div>
          ) : (
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-secondary text-xs text-muted-foreground">
              ?
            </div>
          )}
          <p className="text-center text-xs font-medium text-foreground">{homeName}</p>
        </div>

        {/* Score */}
        <div className="flex items-center gap-3 px-4">
          <span
            className={`text-3xl font-bold ${
              isCompleted ? "text-foreground" : "text-muted-foreground/40"
            }`}
          >
            {homeScore ?? "-"}
          </span>
          <span className="text-lg text-muted-foreground">:</span>
          <span
            className={`text-3xl font-bold ${
              isCompleted ? "text-foreground" : "text-muted-foreground/40"
            }`}
          >
            {awayScore ?? "-"}
          </span>
        </div>

        {/* Away team */}
        <div className="flex flex-1 flex-col items-center gap-2">
          {awayLogo ? (
            <div className="relative h-12 w-12 overflow-hidden rounded-full">
              <Image src={getLogoUrl(awayLogo)} alt={awayName} fill className="object-cover" sizes="48px" />
            </div>
          ) : (
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-secondary text-xs text-muted-foreground">
              ?
            </div>
          )}
          <p className="text-center text-xs font-medium text-foreground">{awayName}</p>
        </div>
      </div>
    </div>
  )
}
